version: "3.7"

services:
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: [redis-server]
    volumes:
      - redis-data:/data

  mysql:
    image: mysql/mysql-server:5.7
    command: ["--bind-address=0.0.0.0"]
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # コンテナ名
  app:
    # Dockerfileの場所
    build:
      context: .
      dockerfile: Dockerfile
    # 環境変数
    environment:
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    # localhost3000番ポートあての通信を、コンテナ3000番ポートに転送
    ports:
      - "3000:3000"
    # 先に起動したいサービス名
    depends_on:
      - mysql
      - nginx
      - redis
    # 以下のディレクトリを、ホストOS(PC)上で定義したボリュームにマウント
    volumes:
      - .:/app
      - fav_map_bundle:/app/vendor/bundle
      - fav_map_node_modules:/app/node_modules
      - fav_map_public:/app/public
      - fav_map_socket:/app/sockets
    # command: ["bundle", "exec", "puma", "-b", "unix:///app/sockets/puma.sock"]

  nginx:
    image: nginx:1.17
    ports:
      - "8080:80"
    command: [nginx]
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - fav_map_public:/app/public
      - fav_map_socket:/app/sockets

# ホストOS(PC)上にボリュームを定義
volumes:
  mysql-data:
    driver: local
  fav_map_bundle:
    driver: local
  fav_map_node_modules:
    driver: local
  fav_map_public:
    driver: local
  fav_map_socket:
    driver: local
  redis-data:
    driver: local